chatterpy-backend/accounts/urls.py
from django.urls import path

from .views import *

app_name = "accounts"

urlpatterns = [
    path("log-in/", LogInView.as_view(), name="log_in"),
    path("log-out/", LogOutView.as_view(), name="log_out"),
    path("resend/activation-code/", ResendActivationCodeView.as_view(), name="resend_activation_code",),
    path("sign-up/", SignUpView.as_view(), name="sign_up"),
    path("activate/<code>/", ActivateView.as_view(), name="activate"),
    path("add-user/", AddUserView.as_view(), name="add_user"),
    path("invite-user/", InviteUserView.as_view(), name="invite_user"),
    path("invitation/<account>/<company>/<email>/", InviteSignUpView.as_view(), name="invitation",),
    path("restore/password/", RestorePasswordView.as_view(), name="restore_password"),
    path("restore/password/done/", RestorePasswordDoneView.as_view(), name="restore_password_done",),
    path("restore/<uidb64>/<token>/", RestorePasswordConfirmView.as_view(), name="restore_password_confirm",),
    path("remind/username/", RemindUsernameView.as_view(), name="remind_username"),
    path("change/profile/", ChangeProfileView.as_view(), name="change_profile"),
    path("change/password/", ChangePasswordView.as_view(), name="change_password"),
    path("change/email/", ChangeEmailView.as_view(), name="change_email"),
    path("change/email/<code>/", ChangeEmailActivateView.as_view(), name="change_email_activation",),
]

chatterpy-backend/chatterpy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers

from dj_rest_auth.registration.views import VerifyEmailView

from accounts import viewsets as account_viewsets
from contacts import views as contacts_viewsets
from automations import views as automations_viewsets
from emails import views as email_viewsets

# from contact import views as contact_viewsets
# from chat import views as chat_viewsets

router = routers.DefaultRouter()
router.register(r"users", account_viewsets.UserViewSet)
router.register(r"accounts", account_viewsets.AccountViewSet)
router.register(r"numbers", account_viewsets.NumberViewSet)
router.register(r"contacts", contacts_viewsets.ContactViewSet)
router.register(r"collections", contacts_viewsets.CollectionViewSet)
router.register(r"DNM", contacts_viewsets.DNMViewSet)
router.register(r"automations", automations_viewsets.AutomationViewSet)
router.register(r"datasources", email_viewsets.DataSourceViewSet)
router.register(r"emails", email_viewsets.EmailViewSet)
router.register(r"templates", email_viewsets.TemplateViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("v1/", include(router.urls)),
    path("api/", include(("conversations.urls", "conversations"), namespace="conversations")),
    # path("api/", include("automations.urls")),
    # path("api/", include("contacts.urls")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("auth/", include("dj_rest_auth.urls")),
    path("auth/registration/", include("dj_rest_auth.registration.urls")),
    path("auth/account-confirm-email/", VerifyEmailView.as_view(), name="account_email_verification_sent"),
    path("accounts/", include("accounts.urls")),
    path("auto/", include("emails.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""chatterpy_test URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

chatterpy-backend/emails/urls.py
from django.urls import path
from .views import incoming_message, incoming_emails, message_status

urlpatterns = [
    path("incoming-message/3VPt0RIy43ZdBcNR", incoming_message),
    path("incoming-emails/V623LVzvFzMN7BAP", incoming_emails),
    path("message-status/44", message_status)
]

chatterpy-backend/accounts/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django_better_admin_arrayfield.models.fields import ArrayField
from django.dispatch import receiver
from django.db.models.signals import post_save
from rest_framework.authtoken.models import Token
from allauth.account.models import EmailAddress


class Account(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    credits = models.IntegerField(_("Credits"), default=0)
    company_name = models.CharField(_("Company Name"), default="", max_length=50)
    company_size = models.SmallIntegerField(_("Company Size"), default=1)
    enterprise_price = models.FloatField(_("Enterprise price"), default=0.0)
    enterprise_credits = models.IntegerField(_("Enterprise credits"), default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


class Number(models.Model):
    phone_number = models.CharField(_("Phone number"), max_length=30, null=True, blank=True)
    account = models.ForeignKey(
        Account, verbose_name=_("Account"), on_delete=models.PROTECT, related_name="numbers", null=True, blank=True,
    )
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.phone_number)


ROLE_USER = "user"
ROLE_MANAGER = "manager"
ROLE_CHOICES = (
    (ROLE_USER, _("Account User")),
    (ROLE_MANAGER, _("Account Manager")),
)


class UserManager(BaseUserManager):
    def create_user(self, email, username, password, **kwargs):
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        user = self.model(email=self.normalize_email(email), username=username, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        # Create Allauth Email object and send Email Confirmation
        allauth_email = EmailAddress.objects.create(user=user, email=email, primary=True, verified=False)
        allauth_email.send_confirmation()
        return user

    # Used for test cases
    def create_vertified_user(self, email, username, password, **kwargs):
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        user = self.model(email=self.normalize_email(email), username=username, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        # Without a verified email dj_rest_auth endpoints will not allow users to login and get their JWT tokens
        EmailAddress.objects.create(user=user, email=email, primary=True, verified=True)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(email, password=password, username=username,)
        user.is_superuser = True
        user.is_staff = True
        user.set_password(password)
        user.save(using=self._db)
        # EmailAddress.objects.create(user=user, email=email, primary=True, verified=True)
        # allauth_email.send_confirmation()
        return user


class User(AbstractUser):
    def upload_to(instance, filename):
        return "profiles/{0}/{1}".format(instance.id, filename)

    account = models.ForeignKey(
        Account, verbose_name=_("Account"), on_delete=models.SET_NULL, null=True, blank=True, related_name="users",
    )
    phone_number = models.CharField(_("Phone number"), max_length=30, null=True, blank=True)
    file = models.ImageField(blank=True, null=True, upload_to=upload_to)
    first_name = models.CharField(blank=True, null=True, max_length=30, verbose_name="first name")
    last_name = models.CharField(blank=True, null=True, max_length=150, verbose_name="last name")
    role = models.CharField(_("Role"), choices=ROLE_CHOICES, max_length=7, default=ROLE_MANAGER)
    is_account_manager = models.BooleanField(default=False)
    objects = UserManager()

    def __str__(self):
        return self.email

    class Meta:
        db_table = "auth_user"
        verbose_name = "User"


class Activation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)


@receiver(post_save, sender=User)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

chatterpy-backend/accounts/templates/accounts/add_user.html
{% extends 'account_base.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block title %}Add User{% endblock %}

{% block content %}

    <h4>{% trans 'Add User' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-success">{% trans 'Add' %}</button>

    </form>

{% endblock %}

chatterpy-backend/accounts/templates/accounts/invite_user.html
{% extends 'account_base.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block title %}Invite user{% endblock %}

{% block content %}

    <h4>{% trans 'Invite user' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

{% endblock %}

chatterpy-backend/accounts/templates/accounts/log_out.html
{% extends 'account_base.html' %}

{% load i18n %}

{% block title %}Logged out{% endblock %}

{% block content %}

    <h4>{% trans 'Logged out' %}</h4>

    <p>
        {% trans 'Thanks for spending some quality time with the site today.' %}
    </p>

    <p>
        <a href="{% url 'accounts:log_in' %}">{% trans 'Log in again' %}</a>
    </p>

{% endblock %}

chatterpy-backend/accounts/templates/accounts/remind_username.html
{% extends 'account_base.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block title %}Remind a username{% endblock %}

{% block content %}

    <h4>{% trans 'Remind a username' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

chatterpy-backend/accounts/templates/accounts/resend_activation_code.html
{% extends 'account_base.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block title %}Resend an activation code{% endblock %}

{% block content %}

    <h4>{% trans 'Resend an activation code' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

chatterpy-backend/accounts/templates/accounts/restore_password.html
{% extends 'account_base.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block title %}Restore password{% endblock %}

{% block content %}

    <h4>{% trans 'Restore password' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

chatterpy-backend/accounts/templates/accounts/restore_password_confirm.html
{% extends 'account_base.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block title %}Restore password{% endblock %}

{% block content %}

    <h4>{% trans 'Restore password' %}</h4>

    {% if validlink %}

        <p>
            {% trans 'Please enter your new password twice so we can verify you typed it in correctly.' %}
        </p>

        <form method="post">

            {% csrf_token %}
            {% bootstrap_form form %}

            <button class="btn btn-success">{% trans 'Change' %}</button>

        </form>

    {% else %}

        <div class="alert alert-danger">
            {% trans 'The password reset link was invalid, possibly because it has already been used. Please request a new password reset.' %}
        </div>

    {% endif %}

{% endblock %}

chatterpy-backend/accounts/templates/accounts/restore_password_done.html
{% extends 'account_base.html' %}

{% load i18n %}

{% block title %}Restore password{% endblock %}

{% block content %}

    <h4>{% trans 'Restore password' %}</h4>

    <div>
        {% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered." %}
        {% trans 'You should receive them shortly.' %}

        <br>

        {% trans "If you don't receive an email, please make sure you've entered the address you signed up with, and check your spam folder." %}
    </div>

{% endblock %}

chatterpy-backend/accounts/templates/accounts/sign-in.html
{% extends 'chatterpy/base.html' %}

{% load static %}

{% block title %}Sign In{% endblock %}

{% block content %}
<!-- =============Hero Area============= -->
<section class="hero-area bg_img" data-background="{% static 'chatterpy/images/page-header.jpg' %}">
    <div class="container">
        <h1 class="title m-0">my account</h1>
    </div>
</section>
<div class="breadcrumb-section">
    <div class="container">
        <ul class="breadcrumb">
            <li>
                <a>Home</a>
            </li>
            <li>
                sign-in
            </li>
        </ul>
    </div>
</div>
<!-- =============Hero Area============= -->

<!--=================Account Section================= -->
<section class="account-section padding-top padding-bottom bg_img bg_right_bottom"
    data-background="{% static 'chatterpy/images/account/account-bg.png' %}">
    <div class="container">
        <div class="account-wrapper">
            <div class="account-area">
                <h3 class="account-title">sign-in your account</h3>
                <form method="post" class="sign-in-form">{% csrf_token %}
                    <div class="form-group">
                        <input type="email" name="email" placeholder="Email" id="id_email" required>
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" placeholder="Password" id="id_password" required>
                        <span class="view-pass" id="view-pass-01">
                            <i class="flaticon-eye"></i>
                        </span>
                    </div>
                    <div class="form-group w-100 checkgroup">
                        <input type="checkbox" name="remember_me" id="id_remember_me">
                        <label for="id_remember_me">Remember me</label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login Account">
                    </div>
                </form>
                <div class="forget-pass-group d-flex flex-wrap justify-content-between">
                    <div class="forget-pass">
                        <p><a href="{% url 'accounts:restore_password' %}">forget password</a></p>
                    </div>
                    <div class="no-account">
                        <p>Have Not Account in Here? <a href="{% url 'accounts:sign_up' %}">Sign-Up</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--=================Account Section================= -->

<!--=================Sponsor Section================= -->
<div class="sponsor-section padding-top padding-bottom">
    <div class="container">
        <div class="sponsor-slider">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="{% static 'chatterpy/images/sponsor/sponsor01.png' %}" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="{% static 'chatterpy/images/sponsor/sponsor02.png' %}" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="{% static 'chatterpy/images/sponsor/sponsor03.png' %}" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="{% static 'chatterpy/images/sponsor/sponsor04.png' %}" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="{% static 'chatterpy/images/sponsor/sponsor05.png' %}" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="{% static 'chatterpy/images/sponsor/sponsor06.png' %}" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="{% static 'chatterpy/images/sponsor/sponsor07.png' %}" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="{% static 'chatterpy/images/sponsor/sponsor08.png' %}" alt="sponsor">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--=================Sponsor Section================= -->
{% endblock %}

chatterpy-backend/accounts/templates/accounts/sign-up.html
{% extends 'chatterpy/base.html' %}

{% load static %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<!-- =============Hero Area============= -->
<section class="hero-area bg_img" data-background="{% static 'chatterpy/images/page-header.jpg' %}">
    <div class="container">
        <h1 class="title m-0">my account</h1>
    </div>
</section>
<div class="breadcrumb-section">
    <div class="container">
        <ul class="breadcrumb">
            <li>
                <a>Home</a>
            </li>
            <li>
                sign-up
            </li>
        </ul>
    </div>
</div>
<!-- =============Hero Area============= -->

<!--=================Account Section================= -->
<section class="account-section padding-top padding-bottom bg_img bg_xxl_contain bg_right_bottom"
    data-background="{% static 'chatterpy/images/account/account-bg.png' %}">
    <div class="container">
        <div class="account-wrapper">
            <div class="account-area">
                <h3 class="account-title">create new account</h3>
                <form method="post" class="sign-up-form">{% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="first_name" placeholder="First Name">
                    </div>
                    <div class="form-group">
                        <input type="text" name="last_name" placeholder="Last Name">
                    </div>
                    <div class="form-group">
                        <input type="text" name="company_name" placeholder="Company Name">
                    </div>
                    <div class="form-group">
                        <input type="text" name="phone_number" placeholder="Phone Number">
                    </div>
                    <div class="form-group w-100">
                        <input type="text" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password1" placeholder="Password" id="my-input-02">
                        <span class="view-pass" id="view-pass-02">
                            <i class="flaticon-eye"></i>
                        </span>
                    </div>
                    <div class="form-group">
                        <input type="password" name="password2" placeholder="Re-Password" id="my-input-03">
                        <span class="view-pass" id="view-pass-03">
                            <i class="flaticon-eye"></i>
                        </span>
                    </div>
                    <div class="form-group w-100">
                        <input type="submit" value="Create Account">
                    </div>
                </form>
                <div class="forget-pass-group text-center m-0 mt-md-3">
                    <p>Already have an Account? <a href="{% url 'accounts:log_in' %}">Sign-In</a></p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--=================Account Section================= -->

<!--=================Sponsor Section================= -->
<div class="sponsor-section padding-top padding-bottom">
    <div class="container">
        <div class="sponsor-slider">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="./assets/images/sponsor/sponsor01.png" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="./assets/images/sponsor/sponsor02.png" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="./assets/images/sponsor/sponsor03.png" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="./assets/images/sponsor/sponsor04.png" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="./assets/images/sponsor/sponsor05.png" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="./assets/images/sponsor/sponsor06.png" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="./assets/images/sponsor/sponsor07.png" alt="sponsor">
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="sponsor-thumb">
                        <img src="./assets/images/sponsor/sponsor08.png" alt="sponsor">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--=================Sponsor Section================= -->
{% endblock %}